apiVersion: v1
kind: Secret
metadata:
  name: crossplane-dev-secret
  namespace: crossplane-system
type: Opaque
stringData:
  creds: |
    {
      "type": "service_account",
      "project_id": "crossplane-dev",
      "private_key_id": "<REPLACE_WITH_KEY_ID>",
      "private_key": "<REPLACE_WITH_PRIVATE_KEY>",
      "client_email": "<REPLACE_WITH_SA_EMAIL>",
      "client_id": "<REPLACE_WITH_CLIENT_ID>",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token"
    }
