apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: demo-vm
spec:
  providerConfigRef:
    name: default
  forProvider:
    project: round-vent-480303-q3
    zone: us-central1-a
    machineType: e2-medium
    canIpForward: false
    deletionProtection: false

    tags:
      - demo-vm

    bootDisk:
      - autoDelete: true
        initializeParams:
          - image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
            size: 20
            type: pd-balanced

    networkInterface:
      - subnetworkRef:
          name: demo-subnet
        accessConfig:
          - {}

    metadataStartupScript: |
      #!/bin/bash
      set -eux
      apt-get update
      apt-get install -y nginx
      systemctl enable nginx
      systemctl restart nginx
